{
  "MODEL": {
    "DEVICE": "",
    "ARCHITECTURE": "unet",
    "VIDEO_MODE": "i3d",
    "NUM_CLIPS": 128,
    "merge_num": 2, # 8个clip汇聚成一个
    "align_loss":{
      "mode": "video",
    },
    "feature_merger": {
      "mode":"max",
    },
    "hidden_dimension": 256,
    "video": {
      "encoder": {
        "mode": "featpool+linear",
        "v_feat_len": 512,
        "v_feat_dim": 1024,
        "FEATPOOL": {
          "KERNEL_SIZE": 4,
          "HIDDEN_SIZE": 512
        }
      },
      "gnn": {
        "mode": "GNNv3",
        "GNN_LAYERS": 2,
        "GNN_U": 5.0,
        "GNN_STEP": 0.1
      },
      "temporal_feature_map": {
        "mode": "pool",
      },
      "mask_1": {
        "mode": "sparse",
      },
      "mask_2": {
        "mode": "sparse",
      },
      "proposal_conv": {
        "mode": 'decoupled',
        "HIDDEN_SIZE": 512,
        "KERNEL_SIZE": 17,
        "NUM_STACK_LAYERS": 2
      },
      "LOSS": {
        "iou_bce": {
          "mode": 'decoupled',
          "MIN_IOU": 0.5,
          "MAX_IOU": 1.0
        },
        "ContrastiveLoss": {
          "mode": 'decoupled',
          "TAU_VIDEO": 0.1,
          "TAU_SENT": 0.1,
          "NEGATIVE_VIDEO_IOU": 0.5,
          "NUM_POSTIVE_VIDEO_PROPOSAL": 1,
          "SENT_REMOVAL_IOU": 0.5,
          "MARGIN": 0.4
        },
      }
    },
    "frame": {
      "encoder": {
        "mode": "bimamba",
        "f_feat_dim": 768
      },
      "gnn": {
        "mode": "GNNv3",
        "GNN_LAYERS": 2,
        "GNN_U": 5.0,
        "GNN_STEP": 0.1
      },
      "temporal_feature_map": {
        "mode": "pool",
      },
      "mask_1": {
        "mode": "sparse",
      },
      "mask_2": {
        "mode": "sparse",
      },
      "proposal_conv": {
        "mode": 'decoupled',
        "HIDDEN_SIZE": 512,
        "KERNEL_SIZE": 5,
        "NUM_STACK_LAYERS": 3
      },
      "LOSS": {
        "iou_bce": {
          "mode": 'decoupled',
          "MIN_IOU": 0.3,
          "MAX_IOU": 0.7
        },
        "ContrastiveLoss": {
          "mode": 'decoupled',
          "TAU_VIDEO": 0.1,
          "TAU_SENT": 0.1,
          "NEGATIVE_VIDEO_IOU": 0.5,
          "NUM_POSTIVE_VIDEO_PROPOSAL": 3,
          "SENT_REMOVAL_IOU": 0.5,
          "MARGIN": 0.1
        },
      }
    },
    "text": {
      "encoder": {
        "mode": "one"
      },
      "decoder": {
        "mode": "two"
      }
    },
    "pos_encoding": {
      "mode": "none"
    }
  },
  "DATASETS": {
    "NAME": "SDGANcharades",
    "train_label": "/media/zhangbolin/hu/OSGs/open_source/MAIN_CODE/dataset/Charades_STA/train.json",
    "test_label": "/media/zhangbolin/hu/OSGs/open_source/MAIN_CODE/dataset/Charades_STA/test.json",
    "val_label": "/media/zhangbolin/hu/OSGs/open_source/MAIN_CODE/dataset/Charades_STA/test.json",
    "video_feat": "/media/zhangbolin/datasets/charades/i3d_features.hdf5",
    "nclip_in_v_feat": 512, # charades i3d的每个视频的特征长度不统一，统一插值为512
    "frame_feat": "/media/zhangbolin/datasets/charades/FRAME/frame_feature",
    "VideoSegmentTxt": "",
    "f_feat_dim": 768,
    "object_feat": "",
    "text_feat": "/media/zhangbolin/datasets/charades/text_feature",
    "audio_feat": "",
    "chinese_feat": ""
  },
  "DATALOADER": {
    "NUM_WORKERS": 16
  },
  "SOLVER": {
    "LR": 0.00025,
    "BATCH_SIZE": 16,
    "MILESTONES": "(8, 13)",
    "training_stages": [
      {
        "stage_name": "Lclip",
        "NumberOfEpochs": 5,
        "enabled_modals": [
          "Lv": {'iou_bce': 0.6, 'ContrastiveLoss': 0.6 },
          "Lf": {'iou_bce': 0.4, 'ContrastiveLoss': 0.4 },
          "vf": {'Lclip_align': 1.0},
          "e": {'video_queries_loss':1.0, 'frame_queries_loss':1.0}
        ],
        'enable_print': False,
        'save_dir': "",
        'enable_save': True
      },
      {
        "stage_name": "clip",
        "NumberOfEpochs": 5,
        "enabled_modals": [
          "v": {'iou_bce': 0.6, 'ContrastiveLoss': 0.6 },
          "f": {'iou_bce': 0.4, 'ContrastiveLoss': 0.4 },
          "vf": {'Lclip_align': 1.0},
          "e": {'video_queries_loss':1.0, 'frame_queries_loss':1.0}
        ],
        'enable_print': False,
        'save_dir': "",
        'enable_save': True
      },
      {
        "stage_name": "Lclip",
        "NumberOfEpochs": 5,
        "enabled_modals": [
          "Lv": {'iou_bce': 0.6, 'ContrastiveLoss': 0.6 },
          "Lf": {'iou_bce': 0.4, 'ContrastiveLoss': 0.4 },
          "vf": {'Lclip_align': 1.0},
          "e": {'video_queries_loss':1.0, 'frame_queries_loss':1.0}
        ],
        'enable_print': False,
        'save_dir': "",
        'enable_save': True
      },
      {
        "stage_name": "clip",
        "NumberOfEpochs": 5,
        "enabled_modals": [
          "v": {'iou_bce': 0.6, 'ContrastiveLoss': 0.6 },
          "f": {'iou_bce': 0.4, 'ContrastiveLoss': 0.4 },
          "vf": {'Lclip_align': 1.0},
          "e": {'video_queries_loss':1.0, 'frame_queries_loss':1.0}
        ],
        'enable_print': False,
        'save_dir': "",
        'enable_save': True
      },
    ],
    "test_stage": {
      'enable_print': False,
      'save_dir': "",
      'v_weight': 0.7,
      'f_weight': 0.3,
    },
    "CHECKPOINT_PERIOD": 20,
    "VAL_PERIOD": 20, # 10
    "RESUME": false,
    "RESUME_EPOCH": 211,
    "FREEZE_BERT": 400,
    "SKIP_TEST": 0,
  },
  "TEST": {
    "BATCH_SIZE": 16,
    "NMS_THRESH": 0.4,
    "CONTRASTIVE_SCORE_POW": 0.3
  },
  "validation_functions": ["check_feat_len", "mask_pooling_list"],
  "OUTPUT_DIR": "/media/zhangbolin/hu/OSGs/open_source/checkpoints/charades/"
}