'''
参考：
https://github.com/iLearn-Lab/CVPR25-OSGNet

/media/zhangbolin/hu/OSGs/OSGNet/libs/modeling/my_archs.py
/media/zhangbolin/hu/OSGs/OSGNet/libs/modeling/mamba_blocks.py
'''
import torch
from torch import nn
from einops import rearrange
from mamba_ssm import Mamba
import math
import numpy as np
import torch.nn.functional as F
from mamba_ssm import Mamba
# causal_conv1d import causal_conv1d_fn, causal_conv1d_update
from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn, bimamba_inner_fn, mamba_inner_fn_no_out_proj

layers={}
def register_layer(name):
    def decorator(cls):
        layers[name]=cls
        return cls
    return decorator
blocks={}
def register_block(name):
    def decorator(cls):
        blocks[name]=cls
        return cls
    return decorator

# from https://github.com/rwightman/pytorch-image-models/blob/master/timm/models/layers/weight_init.py
import torch
import math
import warnings


def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    # Cut & paste from PyTorch official master until it's in a few official releases - RW
    # Method based on https://people.sc.fsu.edu/~jburkardt/presentations/truncated_normal.pdf
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    # type: (Tensor, float, float, float, float) -> Tensor
    r"""Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)

class LinearLayer(nn.Module):
    """linear layer configurable with layer normalization, dropout, ReLU."""
    def __init__(self, in_hsz, out_hsz, layer_norm=True, dropout=0.1, relu=True):
        super(LinearLayer, self).__init__()
        self.relu = relu
        self.layer_norm = layer_norm
        if layer_norm:
            self.LayerNorm = LayerNorm(in_hsz)
        layers = [
            nn.Dropout(dropout),
            nn.Linear(in_hsz, out_hsz)
        ]
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        """(N, L, D)"""
        if self.layer_norm:
            x = self.LayerNorm(x)
        x = self.net(x)
        if self.relu:
            x = F.relu(x, inplace=True)
        return x  # (N, L, D)


class MaskedConv1D(nn.Module):
    """
    Masked 1D convolution. Interface remains the same as Conv1d.
    Only support a sub set of 1d convs
    """

    def __init__(
            self,
            in_channels,
            out_channels,
            kernel_size,
            stride=1,
            padding=0,
            dilation=1,
            groups=1,
            bias=True,
            padding_mode='zeros'
    ):
        super().__init__()
        # element must be aligned
        assert (kernel_size % 2 == 1) and (kernel_size // 2 == padding)
        # stride
        self.stride = stride
        self.conv = nn.Conv1d(in_channels, out_channels, kernel_size,
                              stride, padding, dilation, groups, bias, padding_mode)
        # zero out the bias term if it exists
        if bias:
            torch.nn.init.constant_(self.conv.bias, 0.)

    def forward(self, x, mask):
        # x: batch size, feature channel, sequence length,
        # mask: batch size, 1, sequence length (bool)
        B, C, T = x.size()
        # input length must be divisible by stride
        assert T % self.stride == 0

        # conv
        out_conv = self.conv(x)
        # compute the mask
        if self.stride > 1:
            # downsample the mask using nearest neighbor
            out_mask = F.interpolate(
                mask.to(x.dtype),
                size=T // self.stride,
                mode='nearest'
            )
        else:
            # masking out the features
            out_mask = mask.to(x.dtype)

        # masking the output, stop grad to mask
        out_conv = out_conv * out_mask.detach()
        out_mask = out_mask.bool()
        return out_conv, out_mask


class LayerNorm(nn.Module):
    """
    LayerNorm that supports inputs of size B, C, T
    """

    def __init__(
            self,
            num_channels,
            eps=1e-5,
            affine=True,
            device=None,
            dtype=None,
    ):
        super().__init__()
        factory_kwargs = {'device': device, 'dtype': dtype}
        self.num_channels = num_channels
        self.eps = eps
        self.affine = affine

        if self.affine:
            self.weight = nn.Parameter(
                torch.ones([1, num_channels, 1], **factory_kwargs))
            self.bias = nn.Parameter(
                torch.zeros([1, num_channels, 1], **factory_kwargs))
        else:
            self.register_parameter('weight', None)
            self.register_parameter('bias', None)

    def forward(self, x):
        assert x.dim() == 3
        assert x.shape[1] == self.num_channels

        # normalization along C channels
        mu = torch.mean(x, dim=1, keepdim=True)
        res_x = x - mu
        sigma = torch.mean(res_x ** 2, dim=1, keepdim=True)
        out = res_x / torch.sqrt(sigma + self.eps)

        # apply weight and bias
        if self.affine:
            out *= self.weight
            out += self.bias

        return out
class LayerNorm4(nn.Module):
    """
    LayerNorm that supports inputs of size B,O, C, T
    """

    def __init__(
            self,
            num_channels,
            eps=1e-5,
            affine=True,
            device=None,
            dtype=None,
    ):
        super().__init__()
        factory_kwargs = {'device': device, 'dtype': dtype}
        self.num_channels = num_channels
        self.eps = eps
        self.affine = affine

        if self.affine:
            self.weight = nn.Parameter(
                torch.ones([1,1, num_channels, 1], **factory_kwargs))
            self.bias = nn.Parameter(
                torch.zeros([1, 1,num_channels, 1], **factory_kwargs))
        else:
            self.register_parameter('weight', None)
            self.register_parameter('bias', None)

    def forward(self, x):
        assert x.dim() == 4
        assert x.shape[2] == self.num_channels

        # normalization along C channels
        mu = torch.mean(x, dim=2, keepdim=True)
        res_x = x - mu
        sigma = torch.mean(res_x ** 2, dim=2, keepdim=True)
        out = res_x / torch.sqrt(sigma + self.eps)

        # apply weight and bias
        if self.affine:
            out *= self.weight
            out += self.bias

        return out

# helper functions for Transformer blocks
def get_sinusoid_encoding(n_position, d_hid):
    ''' Sinusoid position encoding table '''

    def get_position_angle_vec(position):
        return [position / np.power(10000, 2 * (hid_j // 2) / d_hid) for hid_j in range(d_hid)]

    sinusoid_table = np.array([get_position_angle_vec(pos_i) for pos_i in range(n_position)])
    sinusoid_table[:, 0::2] = np.sin(sinusoid_table[:, 0::2])  # dim 2i
    sinusoid_table[:, 1::2] = np.cos(sinusoid_table[:, 1::2])  # dim 2i+1

    # return a tensor of size 1 C T
    return torch.FloatTensor(sinusoid_table).unsqueeze(0).transpose(1, 2)


# attention / transformers
@register_block('MaskedMHA')
class MaskedMHA(nn.Module):
    """
    Multi Head Attention with mask

    Modified from https://github.com/karpathy/minGPT/blob/master/mingpt/model.py
    """

    def __init__(
            self,
            n_embd,  # dimension of the input embedding
            n_head,  # number of heads in multi-head self-attention
            attn_pdrop=0.0,  # dropout rate for the attention map
            proj_pdrop=0.0  # dropout rate for projection op
    ):
        super().__init__()
        assert n_embd % n_head == 0
        self.n_embd = n_embd
        self.n_head = n_head
        self.n_channels = n_embd // n_head
        self.scale = 1.0 / math.sqrt(self.n_channels)

        # key, query, value projections for all heads
        # it is OK to ignore masking, as the mask will be attached on the attention
        self.key = nn.Conv1d(self.n_embd, self.n_embd, 1)
        self.query = nn.Conv1d(self.n_embd, self.n_embd, 1)
        self.value = nn.Conv1d(self.n_embd, self.n_embd, 1)

        # regularization
        self.attn_drop = nn.Dropout(attn_pdrop)
        self.proj_drop = nn.Dropout(proj_pdrop)

        # output projection
        self.proj = nn.Conv1d(self.n_embd, self.n_embd, 1)

    def forward(self, x, mask, encoder_hidden_states=None, encoder_attention_mask=None):

        # x: batch size, feature channel, sequence length,
        # mask: batch size, 1, sequence length (bool)
        B, C, T = x.size()

        # print("x ", x.shape)
        # print("mask ", mask.shape)
        # print("encoder_hidden_states ", encoder_hidden_states.shape)
        # print("attn_mask ", encoder_attention_mask.shape)

        is_cross_attention = encoder_hidden_states is not None
        if is_cross_attention:
            # calculate query, key, values for all heads in batch
            # (B, nh * hs, T)
            q = self.query(x)
            k = self.key(encoder_hidden_states)
            v = self.value(encoder_hidden_states)
            attn_mask = encoder_attention_mask
        else:
            # calculate query, key, values for all heads in batch
            # (B, nh * hs, T)
            k = self.key(x)
            q = self.query(x)
            v = self.value(x)
            attn_mask = mask

        # move head forward to be the batch dim
        # (B, nh * hs, T) -> (B, nh, T, hs)
        k = k.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        q = q.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        v = v.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        # print("k ", k.shape)
        # print("q ", q.shape)
        # print("v ", v.shape)
        # self-attention: (B, nh, T, hs) x (B, nh, hs, T) -> (B, nh, T, T)
        att = (q * self.scale) @ k.transpose(-2, -1)
        # print("att 1 ", att.shape)
        # prevent q from attending to invalid tokens
        att = att.masked_fill(torch.logical_not(attn_mask[:, :, None, :]), float('-inf'))
        # print("att 2 ", att.shape)
        # softmax attn
        att = F.softmax(att, dim=-1)
        att = att.masked_fill(torch.logical_not(attn_mask[:, :, None, :]), float('0'))

        # print("att 3 ", att.shape)
        att = self.attn_drop(att)
        # (B, nh, T, T) x (B, nh, T, hs) -> (B, nh, T, hs)
        out = att @ (v * attn_mask[:, :, :, None].to(v.dtype))
        # print("out 1 ", out.shape)
        # re-assemble all head outputs side by side
        out = out.transpose(2, 3).contiguous().view(B, C, -1)

        # output projection + skip connection
        out = self.proj_drop(self.proj(out)) * mask.to(out.dtype)
        return out, mask

@register_block('MaskedMHCA')
class MaskedMHCA(nn.Module):
    """
    Multi Head Conv Attention with mask

    Add a depthwise convolution within a standard MHA
    The extra conv op can be used to
    (1) encode relative position information (relacing position encoding);
    (2) downsample the features if needed;
    (3) match the feature channels

    Note: With current implementation, the downsampled feature will be aligned
    to every s+1 time step, where s is the downsampling stride. This allows us
    to easily interpolate the corresponding positional embeddings.

    Modified from https://github.com/karpathy/minGPT/blob/master/mingpt/model.py
    """

    def __init__(
            self,
            n_embd,  # dimension of the output features
            n_head,  # number of heads in multi-head self-attention
            n_qx_stride=1,  # dowsampling stride for query and input
            n_kv_stride=1,  # downsampling stride for key and value
            attn_pdrop=0.0,  # dropout rate for the attention map
            proj_pdrop=0.0,  # dropout rate for projection op
    ):
        super().__init__()
        assert n_embd % n_head == 0
        self.n_embd = n_embd
        self.n_head = n_head
        self.n_channels = n_embd // n_head
        self.scale = 1.0 / math.sqrt(self.n_channels)

        # conv/pooling operations
        assert (n_qx_stride == 1) or (n_qx_stride % 2 == 0)
        assert (n_kv_stride == 1) or (n_kv_stride % 2 == 0)
        self.n_qx_stride = n_qx_stride
        self.n_kv_stride = n_kv_stride

        # query conv (depthwise)
        kernel_size = self.n_qx_stride + 1 if self.n_qx_stride > 1 else 3
        stride, padding = self.n_kv_stride, kernel_size // 2
        # 1d depthwise conv
        self.query_conv = MaskedConv1D(
            self.n_embd, self.n_embd, kernel_size,
            stride=stride, padding=padding, groups=self.n_embd, bias=False
        )
        # layernorm
        self.query_norm = LayerNorm(self.n_embd)

        # key, value conv (depthwise)
        kernel_size = self.n_kv_stride + 1 if self.n_kv_stride > 1 else 3
        stride, padding = self.n_kv_stride, kernel_size // 2
        # 1d depthwise conv
        self.key_conv = MaskedConv1D(
            self.n_embd, self.n_embd, kernel_size,
            stride=stride, padding=padding, groups=self.n_embd, bias=False
        )
        self.key_norm = LayerNorm(self.n_embd)
        self.value_conv = MaskedConv1D(
            self.n_embd, self.n_embd, kernel_size,
            stride=stride, padding=padding, groups=self.n_embd, bias=False
        )
        # layernorm
        self.value_norm = LayerNorm(self.n_embd)

        # key, query, value projections for all heads
        # it is OK to ignore masking, as the mask will be attached on the attention
        self.key = nn.Conv1d(self.n_embd, self.n_embd, 1)
        self.query = nn.Conv1d(self.n_embd, self.n_embd, 1)
        self.value = nn.Conv1d(self.n_embd, self.n_embd, 1)

        # regularization
        self.attn_drop = nn.Dropout(attn_pdrop)
        self.proj_drop = nn.Dropout(proj_pdrop)

        # output projection
        self.proj = nn.Conv1d(self.n_embd, self.n_embd, 1)

    def forward(self, x, mask):
        # x: batch size, feature channel, sequence length,
        # mask: batch size, 1, sequence length (bool)
        B, C, T = x.size()
        # print("self-attention")
        # print("x ", x.shape)
        # print("mask ", mask.shape)

        # query conv -> (B, nh * hs, T')
        q, qx_mask = self.query_conv(x, mask)
        q = self.query_norm(q)
        # key, value conv -> (B, nh * hs, T'')
        k, kv_mask = self.key_conv(x, mask)
        k = self.key_norm(k)
        v, _ = self.value_conv(x, mask)
        v = self.value_norm(v)

        # projections
        q = self.query(q)
        k = self.key(k)
        v = self.value(v)

        # print("k ", k.shape)
        # print("q ", q.shape)
        # print("v ", v.shape)

        # move head forward to be the batch dim
        # (B, nh * hs, T'/T'') -> (B, nh, T'/T'', hs)
        k = k.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        q = q.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        v = v.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)

        # self-attention: (B, nh, T', hs) x (B, nh, hs, T'') -> (B, nh, T', T'')
        att = (q * self.scale) @ k.transpose(-2, -1)
        # print("att 1 ", att.shape)
        # prevent q from attending to invalid tokens
        att = att.masked_fill(torch.logical_not(kv_mask[:, :, None, :]), float('-inf'))
        # print("att 2 ", att.shape)
        # softmax attn
        att = F.softmax(att, dim=-1)
        att = att.masked_fill(torch.logical_not(kv_mask[:, :, None, :]), float('0'))
        # print("att 3 ", att.shape)
        att = self.attn_drop(att)
        # (B, nh, T', T'') x (B, nh, T'', hs) -> (B, nh, T', hs)
        out = att @ (v * kv_mask[:, :, :, None].to(v.dtype))
        # print("out 1 ", out.shape)
        # re-assemble all head outputs side by side
        out = out.transpose(2, 3).contiguous().view(B, C, -1)

        # output projection + skip connection
        out = self.proj_drop(self.proj(out)) * qx_mask.to(out.dtype)
        return out, qx_mask

@register_block('LocalMaskedMHCA')
class LocalMaskedMHCA(nn.Module):
    """
    Local Multi Head Conv Attention with mask

    Add a depthwise convolution within a standard MHA
    The extra conv op can be used to
    (1) encode relative position information (relacing position encoding);
    (2) downsample the features if needed;
    (3) match the feature channels

    Note: With current implementation, the downsampled feature will be aligned
    to every s+1 time step, where s is the downsampling stride. This allows us
    to easily interpolate the corresponding positional embeddings.

    The implementation is fairly tricky, code reference from
    https://github.com/huggingface/transformers/blob/master/src/transformers/models/longformer/modeling_longformer.py
    """

    def __init__(
            self,
            n_embd,  # dimension of the output features
            n_head,  # number of heads in multi-head self-attention
            window_size,  # size of the local attention window
            n_qx_stride=1,  # dowsampling stride for query and input
            n_kv_stride=1,  # downsampling stride for key and value
            attn_pdrop=0.0,  # dropout rate for the attention map
            proj_pdrop=0.0,  # dropout rate for projection op
            use_rel_pe=False  # use relative position encoding
    ):
        super().__init__()
        assert n_embd % n_head == 0
        self.n_embd = n_embd
        self.n_head = n_head
        self.n_channels = n_embd // n_head
        self.scale = 1.0 / math.sqrt(self.n_channels)
        self.window_size = window_size
        self.window_overlap = window_size // 2
        # must use an odd window size
        assert self.window_size > 1 and self.n_head >= 1
        self.use_rel_pe = use_rel_pe

        # conv/pooling operations
        assert (n_qx_stride == 1) or (n_qx_stride % 2 == 0)
        assert (n_kv_stride == 1) or (n_kv_stride % 2 == 0)
        self.n_qx_stride = n_qx_stride
        self.n_kv_stride = n_kv_stride

        # query conv (depthwise)
        kernel_size = self.n_qx_stride + 1 if self.n_qx_stride > 1 else 3
        stride, padding = self.n_kv_stride, kernel_size // 2
        # 1d depthwise conv
        self.query_conv = MaskedConv1D(
            self.n_embd, self.n_embd, kernel_size,
            stride=stride, padding=padding, groups=self.n_embd, bias=False
        )
        # layernorm
        self.query_norm = LayerNorm(self.n_embd)

        # key, value conv (depthwise)
        kernel_size = self.n_kv_stride + 1 if self.n_kv_stride > 1 else 3
        stride, padding = self.n_kv_stride, kernel_size // 2
        # 1d depthwise conv
        self.key_conv = MaskedConv1D(
            self.n_embd, self.n_embd, kernel_size,
            stride=stride, padding=padding, groups=self.n_embd, bias=False
        )
        self.key_norm = LayerNorm(self.n_embd)
        self.value_conv = MaskedConv1D(
            self.n_embd, self.n_embd, kernel_size,
            stride=stride, padding=padding, groups=self.n_embd, bias=False
        )
        # layernorm
        self.value_norm = LayerNorm(self.n_embd)

        # key, query, value projections for all heads
        # it is OK to ignore masking, as the mask will be attached on the attention
        self.key = nn.Conv1d(self.n_embd, self.n_embd, 1)
        self.query = nn.Conv1d(self.n_embd, self.n_embd, 1)
        self.value = nn.Conv1d(self.n_embd, self.n_embd, 1)

        # regularization
        self.attn_drop = nn.Dropout(attn_pdrop)
        self.proj_drop = nn.Dropout(proj_pdrop)

        # output projection
        self.proj = nn.Conv1d(self.n_embd, self.n_embd, 1)

        # relative position encoding
        if self.use_rel_pe:
            self.rel_pe = nn.Parameter(
                torch.zeros(1, 1, self.n_head, self.window_size))
            trunc_normal_(self.rel_pe, std=(2.0 / self.n_embd) ** 0.5)

    @staticmethod
    def _chunk(x, window_overlap):
        """convert into overlapping chunks. Chunk size = 2w, overlap size = w"""
        # x: B x nh, T, hs
        # non-overlapping chunks of size = 2w -> B x nh, T//2w, 2w, hs
        x = x.view(
            x.size(0),
            x.size(1) // (window_overlap * 2),
            window_overlap * 2,
            x.size(2),
        )

        # use `as_strided` to make the chunks overlap with an overlap size = window_overlap
        chunk_size = list(x.size())
        chunk_size[1] = chunk_size[1] * 2 - 1
        chunk_stride = list(x.stride())
        chunk_stride[1] = chunk_stride[1] // 2

        # B x nh, #chunks = T//w - 1, 2w, hs
        return x.as_strided(size=chunk_size, stride=chunk_stride)

    @staticmethod
    def _pad_and_transpose_last_two_dims(x, padding):
        """pads rows and then flips rows and columns"""
        # padding value is not important because it will be overwritten
        x = nn.functional.pad(x, padding)
        x = x.view(*x.size()[:-2], x.size(-1), x.size(-2))
        return x

    @staticmethod
    def _mask_invalid_locations(input_tensor, affected_seq_len):
        beginning_mask_2d = input_tensor.new_ones(affected_seq_len, affected_seq_len + 1).tril().flip(dims=[0])
        beginning_mask = beginning_mask_2d[None, :, None, :]
        ending_mask = beginning_mask.flip(dims=(1, 3))
        beginning_input = input_tensor[:, :affected_seq_len, :, : affected_seq_len + 1]
        beginning_mask = beginning_mask.expand(beginning_input.size())
        # `== 1` converts to bool or uint8
        beginning_input.masked_fill_(beginning_mask == 1, -float("inf"))
        ending_input = input_tensor[:, -affected_seq_len:, :, -(affected_seq_len + 1):]
        ending_mask = ending_mask.expand(ending_input.size())
        # `== 1` converts to bool or uint8
        ending_input.masked_fill_(ending_mask == 1, -float("inf"))

    @staticmethod
    def _pad_and_diagonalize(x):
        """
        shift every row 1 step right, converting columns into diagonals.
        Example::
              chunked_hidden_states: [ 0.4983,  2.6918, -0.0071,  1.0492,
                                       -1.8348,  0.7672,  0.2986,  0.0285,
                                       -0.7584,  0.4206, -0.0405,  0.1599,
                                       2.0514, -1.1600,  0.5372,  0.2629 ]
              window_overlap = num_rows = 4
             (pad & diagonalize) =>
             [ 0.4983,  2.6918, -0.0071,  1.0492, 0.0000,  0.0000,  0.0000
               0.0000,  -1.8348,  0.7672,  0.2986,  0.0285, 0.0000,  0.0000
               0.0000,  0.0000, -0.7584,  0.4206, -0.0405,  0.1599, 0.0000
               0.0000,  0.0000,  0.0000, 2.0514, -1.1600,  0.5372,  0.2629 ]
        """
        total_num_heads, num_chunks, window_overlap, hidden_dim = x.size()
        # total_num_heads x num_chunks x window_overlap x (hidden_dim+window_overlap+1).
        x = nn.functional.pad(
            x, (0, window_overlap + 1)
        )
        # total_num_heads x num_chunks x window_overlap*window_overlap+window_overlap
        x = x.view(total_num_heads, num_chunks, -1)
        # total_num_heads x num_chunks x window_overlap*window_overlap
        x = x[:, :, :-window_overlap]
        x = x.view(
            total_num_heads, num_chunks, window_overlap, window_overlap + hidden_dim
        )
        x = x[:, :, :, :-1]
        return x

    def _sliding_chunks_query_key_matmul(
            self, query, key, num_heads, window_overlap
    ):
        """
        Matrix multiplication of query and key tensors using with a sliding window attention pattern. This implementation splits the input into overlapping chunks of size 2w with an overlap of size w (window_overlap)
        """
        # query / key: B*nh, T, hs
        bnh, seq_len, head_dim = query.size()
        batch_size = bnh // num_heads
        assert seq_len % (window_overlap * 2) == 0
        assert query.size() == key.size()

        chunks_count = seq_len // window_overlap - 1

        # B * num_heads, head_dim, #chunks=(T//w - 1), 2w
        chunk_query = self._chunk(query, window_overlap)
        chunk_key = self._chunk(key, window_overlap)

        # matrix multiplication
        # bcxd: batch_size * num_heads x chunks x 2window_overlap x head_dim
        # bcyd: batch_size * num_heads x chunks x 2window_overlap x head_dim
        # bcxy: batch_size * num_heads x chunks x 2window_overlap x 2window_overlap
        diagonal_chunked_attention_scores = torch.einsum(
            "bcxd,bcyd->bcxy", (chunk_query, chunk_key))

        # convert diagonals into columns
        # B * num_heads, #chunks, 2w, 2w+1
        diagonal_chunked_attention_scores = self._pad_and_transpose_last_two_dims(
            diagonal_chunked_attention_scores, padding=(0, 0, 0, 1)
        )

        # allocate space for the overall attention matrix where the chunks are combined. The last dimension
        # has (window_overlap * 2 + 1) columns. The first (window_overlap) columns are the window_overlap lower triangles (attention from a word to
        # window_overlap previous words). The following column is attention score from each word to itself, then
        # followed by window_overlap columns for the upper triangle.
        diagonal_attention_scores = diagonal_chunked_attention_scores.new_empty(
            (batch_size * num_heads, chunks_count + 1, window_overlap, window_overlap * 2 + 1)
        )

        # copy parts from diagonal_chunked_attention_scores into the combined matrix of attentions
        # - copying the main diagonal and the upper triangle
        diagonal_attention_scores[:, :-1, :, window_overlap:] = diagonal_chunked_attention_scores[
                                                                :, :, :window_overlap, : window_overlap + 1
                                                                ]
        diagonal_attention_scores[:, -1, :, window_overlap:] = diagonal_chunked_attention_scores[
                                                               :, -1, window_overlap:, : window_overlap + 1
                                                               ]
        # - copying the lower triangle
        diagonal_attention_scores[:, 1:, :, :window_overlap] = diagonal_chunked_attention_scores[
                                                               :, :, -(window_overlap + 1): -1, window_overlap + 1:
                                                               ]

        diagonal_attention_scores[:, 0, 1:window_overlap, 1:window_overlap] = diagonal_chunked_attention_scores[
                                                                              :, 0, : window_overlap - 1,
                                                                              1 - window_overlap:
                                                                              ]

        # separate batch_size and num_heads dimensions again
        diagonal_attention_scores = diagonal_attention_scores.view(
            batch_size, num_heads, seq_len, 2 * window_overlap + 1
        ).transpose(2, 1)

        self._mask_invalid_locations(diagonal_attention_scores, window_overlap)
        return diagonal_attention_scores

    def _sliding_chunks_matmul_attn_probs_value(
            self, attn_probs, value, num_heads, window_overlap
    ):
        """
        Same as _sliding_chunks_query_key_matmul but for attn_probs and value tensors. Returned tensor will be of the
        same shape as `attn_probs`
        """
        bnh, seq_len, head_dim = value.size()
        batch_size = bnh // num_heads
        assert seq_len % (window_overlap * 2) == 0
        assert attn_probs.size(3) == 2 * window_overlap + 1
        chunks_count = seq_len // window_overlap - 1
        # group batch_size and num_heads dimensions into one, then chunk seq_len into chunks of size 2 window overlap

        chunked_attn_probs = attn_probs.transpose(1, 2).reshape(
            batch_size * num_heads, seq_len // window_overlap, window_overlap, 2 * window_overlap + 1
        )

        # pad seq_len with w at the beginning of the sequence and another window overlap at the end
        padded_value = nn.functional.pad(value, (0, 0, window_overlap, window_overlap), value=-1)

        # chunk padded_value into chunks of size 3 window overlap and an overlap of size window overlap
        chunked_value_size = (batch_size * num_heads, chunks_count + 1, 3 * window_overlap, head_dim)
        chunked_value_stride = padded_value.stride()
        chunked_value_stride = (
            chunked_value_stride[0],
            window_overlap * chunked_value_stride[1],
            chunked_value_stride[1],
            chunked_value_stride[2],
        )
        chunked_value = padded_value.as_strided(size=chunked_value_size, stride=chunked_value_stride)

        chunked_attn_probs = self._pad_and_diagonalize(chunked_attn_probs)

        context = torch.einsum("bcwd,bcdh->bcwh", (chunked_attn_probs, chunked_value))
        return context.view(batch_size, num_heads, seq_len, head_dim)

    def forward(self, x, mask):
        # x: batch size, feature channel, sequence length,
        # mask: batch size, 1, sequence length (bool)
        B, C, T = x.size()

        # step 1: depth convolutions
        # query conv -> (B, nh * hs, T')
        q, qx_mask = self.query_conv(x, mask)
        q = self.query_norm(q)
        # key, value conv -> (B, nh * hs, T'')
        k, kv_mask = self.key_conv(x, mask)
        k = self.key_norm(k)
        v, _ = self.value_conv(x, mask)
        v = self.value_norm(v)

        # step 2: query, key, value transforms & reshape
        # projections
        q = self.query(q)
        k = self.key(k)
        v = self.value(v)
        # (B, nh * hs, T) -> (B, nh, T, hs)这是必要的，因为要做维度交换
        q = q.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        k = k.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        v = v.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        # view as (B * nh, T, hs)
        q = q.view(B * self.n_head, -1, self.n_channels).contiguous()
        k = k.view(B * self.n_head, -1, self.n_channels).contiguous()
        v = v.view(B * self.n_head, -1, self.n_channels).contiguous()

        # step 3: compute local self-attention with rel pe and masking
        q *= self.scale
        # chunked query key attention -> B, T, nh, 2w+1 = window_size
        att = self._sliding_chunks_query_key_matmul(
            q, k, self.n_head, self.window_overlap)

        # rel pe
        if self.use_rel_pe:
            att += self.rel_pe
        # kv_mask -> B, T'', 1
        inverse_kv_mask = torch.logical_not(
            kv_mask[:, :, :, None].view(B, -1, 1))
        # 0 for valid slot, -inf for masked ones
        float_inverse_kv_mask = inverse_kv_mask.type_as(q).masked_fill(
            inverse_kv_mask, -1e4)
        # compute the diagonal mask (for each local window)
        diagonal_mask = self._sliding_chunks_query_key_matmul(
            float_inverse_kv_mask.new_ones(size=float_inverse_kv_mask.size()),
            float_inverse_kv_mask,
            1,
            self.window_overlap
        )
        att += diagonal_mask

        # ignore input masking for now
        att = nn.functional.softmax(att, dim=-1)
        # softmax sometimes inserts NaN if all positions are masked, replace them with 0
        att = att.masked_fill(
            torch.logical_not(kv_mask.squeeze(1)[:, :, None, None]), 0.0)
        att = self.attn_drop(att)

        # step 4: compute attention value product + output projection
        # chunked attn value product -> B, nh, T, hs
        out = self._sliding_chunks_matmul_attn_probs_value(
            att, v, self.n_head, self.window_overlap)
        # transpose to B, nh, hs, T -> B, nh*hs, T
        out = out.transpose(2, 3).contiguous().view(B, C, -1)
        # output projection + skip connection
        out = self.proj_drop(self.proj(out)) * qx_mask.to(out.dtype)
        return out, qx_mask

from einops import rearrange

    

class ShotMaskedMHA(MaskedMHA):
    """
    Multi Head Attention with mask

    Modified from https://github.com/karpathy/minGPT/blob/master/mingpt/model.py
    """

    def __init__(
            self,
            **kwargs
    ):

        super().__init__(**kwargs)

    def forward(self, x, mask, encoder_hidden_states, encoder_attention_mask,bs_shots):

        # x: 1, feature channel, 1,

        B, C, T = encoder_hidden_states.size()


        q = self.query(x)
        k = self.key(encoder_hidden_states)
        v = self.value(encoder_hidden_states)
        # attn_mask = encoder_attention_mask


        # move head forward to be the batch dim
        # (B, nh * hs, T) -> (B, nh, T, hs)
        k = k.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)
        q = q.view(1, self.n_head, self.n_channels, -1).transpose(2, 3)
        v = v.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)

        # self-attention: (1, nh, 1,hs) x (B, nh, hs, T) -> (B, nh, 1, T)
        att = (q * self.scale) @ k.transpose(-2, -1)

        # att = att.masked_fill(torch.logical_not(attn_mask[:, :, None, :]), float('-inf'))
        outs=[]
        for (attentions,values,shots) in zip(att,v,bs_shots):
            shots=shots[:-1]
            for shot in shots:
                attention=attentions[...,shot[0]:shot[1]]
                attention = F.softmax(attention, dim=-1)
                value=values[:,shot[0]:shot[1],:]#[nh,Ti,hs]
                # ( nh, 1, Ti) x ( nh, Ti, hs) -> ( nh, 1, hs)
                out = att @ v 
                outs.append(out.flatten(0))
        outs=torch.stack(outs,dim=0)#[shot_num,C]
        out = outs.unsqueeze(-1)#[shot_num,C,1]

        # output projection + skip connection
        out = self.proj_drop(self.proj(out)) 
        return out

    def __init__(
            self,
            **kwargs
    ):
        super().__init__(**kwargs)
        self.cross_attn=ShotMaskedMHA(
                kwargs['n_embd'],
                kwargs['n_head'],
            )
    def forward(self, x,  cross_y, shots, pos_embd=None):
        # pre-LN transformer: https://arxiv.org/pdf/2002.04745.pdf
        # x: 1, feature channel, 1,
        #cross_y: bs,C,T
        #shots:bs x [shots_num,2]
        #  downsample in the multi-head local attention
        # out, out_mask = self.attn(self.ln1(x), mask)
        # out_mask=mask
        # out_mask_float = out_mask.to(x.dtype)
        # out = self.pool_skip(x) * out_mask_float + self.drop_path_attn(out)

        # optional cross_modal attention
        # print("inside")
        cross_out = self.cross_attn(self.ln3(x), None, self.ln3(cross_y), None,shots)
        # out_mask_float = out_mask.to(cross_out_mask.dtype)
        out = x+cross_out

        # FFN
        out = out + self.mlp(self.ln2(out)) 
        # optionally add pos_embd to the output
        # if pos_embd is not None:
        #     out += pos_embd * out_mask_float
        return out
@register_block('ObjectMaskedMHA')
class ObjectMaskedMHA(MaskedMHA):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)

    def forward(self,x, mask, encoder_hidden_states, encoder_hidden_states_mask):
        # encoder_hidden_states=src_obj#[bs x maxlen,C,max_seq_len]因为只接2d和3d
        # encoder_hidden_states_mask=src_obj_mask#[bs x maxlen,1,max_seq_len]
        B, C, T = x.size()

        q = self.query(x)
        k = self.key(encoder_hidden_states)
        v = self.value(encoder_hidden_states)

        q = q.view(B, self.n_head, self.n_channels, -1).transpose(2, 3)#[bs,n_h,T,c_h]
        k = k.view(B, -1,self.n_head, self.n_channels, T)#[bs,maxobjlen,n_h,c_h,T]
        v = v.view(B, -1,self.n_head, self.n_channels, T)#[bs,maxobjlen,n_h,c_h,T]
        q=q*self.scale
        # att = torch.einsum('bntc,bonca->bonta',q,k)#[bs,obj,n_h,T,T]这里不对，不应该计算所有帧的物体注意力
        att = torch.einsum('bntc,bonct->bont',q,k)#[bs,obj,n_h,T]
        att_mask=encoder_hidden_states_mask.view(B,-1,1,T)#[bs,obj,1,T]
        att = att.masked_fill(torch.logical_not(att_mask), float('-inf'))#[bs,obj,n_h,T]
        att=rearrange(att,'b o n t  -> b n t o')#[bs,n_h,T, obj]
        att = F.softmax(att, dim=-1)#[bs,n_h,T, obj]#由于存在所有obj都无效的情况，还需要再mask一次
        att_mask=rearrange(att_mask,'b o 1 t -> b 1 t o')
        att=att.masked_fill(torch.logical_not(att_mask), float('0'))#[bs,n_h,T, obj]
        att = self.attn_drop(att)
        v_mask=rearrange(att_mask,'b 1 t o -> b o 1 1 t').to(v.dtype)
        v_masked=v*v_mask
        out = torch.einsum('bnto,bonct->bnct',att,v_masked)#[bs,n_h,c_h,T]
        out = out.reshape(B, C, -1)
        out = self.proj_drop(self.proj(out)) * mask.to(out.dtype)
        return out, mask



class ObjectQueryMaskedMHCA(MaskedMHCA):
    #为了共享参数没办法
    def __init__(self,window_size, **kwargs):
        super().__init__(**kwargs)
        self.window_size=window_size
    def forward(self,x, mask, encoder_hidden_states=None, encoder_hidden_states_mask=None):
        # x:[bs,obj,c,t],mask:[bs*obj,1,t]
        #encoder_hidden_states=src_txt#[bs ,C,max_seq_len]
        # encoder_hidden_states_mask=src_txt_mask#[bs ,1,max_seq_len]
        B,O, C, T = x.size()
        if self.window_size>1:
            r=self.window_size//2
            x_w=torch.nn.functional.pad(x, (r, r))
            x_w=x_w.unfold(dimension=-1,size=3,step=1).permute(0,1,4,2,3)#[b,o,w,c,t]
            x_w=rearrange(x_w,'b o w c t -> (b o w) c t')
            
            
            v_mask=mask.view(B,O,1,T)
            v_mask=torch.nn.functional.pad(v_mask, (r, r))
            v_mask=v_mask.unfold(dimension=-1,size=3,step=1).permute(0,1,4,2,3)#[b,o,w,1,t]

        else:
            x_w=x
            x_w=rearrange(x_w,"b o c t -> (b o) c t")
            v_mask=mask
        x=rearrange(x,"b o c t -> (b o) c t")
        is_cross_attention = encoder_hidden_states is not None
        if is_cross_attention:
            # calculate query, key, values for all heads in batch
            # (B, nh * hs, T)
            q, qx_mask = self.query_conv(x, mask)
            q = self.query_norm(q)
            # key, value conv -> (B, nh * hs, T'')
            k, kv_mask = self.key_conv(encoder_hidden_states, encoder_hidden_states_mask)
            k = self.key_norm(k)
            v, _ = self.value_conv(encoder_hidden_states, encoder_hidden_states_mask)
            v = self.value_norm(v)

            q = self.query(q)
            k = self.key(k)
            v = self.value(v)

        else:
            q, qx_mask = self.query_conv(x, mask)
            q = self.query_norm(q)
            # key, value conv -> (B, nh * hs, T'')
            k, kv_mask = self.key_conv(x_w, v_mask.view(-1,1,T))
            k = self.key_norm(k)
            v, _ = self.value_conv(x_w, v_mask.view(-1,1,T))
            v = self.value_norm(v)


            q = self.query(q)
            k = self.key(k)
            v = self.value(v)



        q = q.view(B,O, self.n_head, self.n_channels, T)
        q=q*self.scale
        if is_cross_attention:
            k = k.view(B, self.n_head, self.n_channels, -1)
            v = v.view(B, self.n_head, self.n_channels, -1)
            att = torch.einsum('bonct,bnca->bonta',q,k)#[bs,obj,n_h,T,txt_len]
            att_mask=encoder_hidden_states_mask.view(B,1,1,1,-1)
            v_mask=encoder_hidden_states_mask.view(B,1,1,-1).to(v.dtype)
            v_masked=v*v_mask
        else:
            k = k.view(B, -1,self.n_head, self.n_channels, T)
            v = v.view(B, -1,self.n_head, self.n_channels, T)
        
            att = torch.einsum('bonct,bwnct->bontw',q,k)#[bs,obj,n_h,T,o*w]
            att_mask=mask.view(B,O,1,T,1)
            v_mask=v_mask.reshape(B,O*self.window_size,1,1,T).to(v.dtype)
            v_masked=v*v_mask
        
        att = att.masked_fill(torch.logical_not(att_mask), float('-inf'))    
        att = F.softmax(att, dim=-1)
        att = self.attn_drop(att)
        att = att.masked_fill(torch.logical_not(att_mask), float('0'))    
        if is_cross_attention:
            out = torch.einsum('bonta,bnca->bonct',att,v_masked)#[bs,o,n_h,c_h,T]
        else:
            out = torch.einsum('bontw,bwnct->bonct',att,v_masked)#[bs,o,n_h,c_h,T]
        out = out.reshape(B*O, C, T)
        out = self.proj_drop(self.proj(out)) * mask.to(out.dtype)
        out = out.reshape(B,O, C, T)
        return out, mask

class ConvBlock(nn.Module):
    """
    A simple conv block similar to the basic block used in ResNet
    """

    def __init__(
            self,
            n_embd,  # dimension of the input features
            kernel_size=3,  # conv kernel size
            n_ds_stride=1,  # downsampling stride for the current layer
            expansion_factor=2,  # expansion factor of feat dims
            n_out=None,  # output dimension, if None, set to input dim
            act_layer=nn.ReLU,  # nonlinear activation used after conv, default ReLU
    ):
        super().__init__()
        # must use odd sized kernel
        assert (kernel_size % 2 == 1) and (kernel_size > 1)
        padding = kernel_size // 2
        if n_out is None:
            n_out = n_embd

        # 1x3 (strided) -> 1x3 (basic block in resnet)
        width = n_embd * expansion_factor
        self.conv1 = MaskedConv1D(
            n_embd, width, kernel_size, n_ds_stride, padding=padding)
        self.conv2 = MaskedConv1D(
            width, n_out, kernel_size, 1, padding=padding)

        # attach downsampling conv op
        if n_ds_stride > 1:
            # 1x1 strided conv (same as resnet)
            self.downsample = MaskedConv1D(n_embd, n_out, 1, n_ds_stride)
        else:
            self.downsample = None

        self.act = act_layer()

    def forward(self, x, mask, pos_embd=None):
        identity = x
        out, out_mask = self.conv1(x, mask)
        out = self.act(out)
        out, out_mask = self.conv2(out, out_mask)

        # downsampling
        if self.downsample is not None:
            identity, _ = self.downsample(x, mask)

        # residual connection
        out += identity
        out = self.act(out)

        return out, out_mask


# drop path: from https://github.com/facebookresearch/SlowFast/blob/master/slowfast/models/common.py
class Scale(nn.Module):
    """
    Multiply the output regression range by a learnable constant value
    """

    def __init__(self, init_value=1.0):
        """
        init_value : initial value for the scalar
        """
        super().__init__()
        self.scale = nn.Parameter(
            torch.tensor(init_value, dtype=torch.float32),
            requires_grad=True
        )

    def forward(self, x):
        """
        input -> scale * input
        """
        return x * self.scale




def reverse_tensor_based_on_mask(x, mask):
    # hidden_states: (B, D, L)
    #         mask:(B,L)
    result = []  # 创建一个张量的副本以保存结果
    for (x_i,mask_i) in zip(x,mask):
        # 获取有效元素的索引
        valid_len=mask_i.sum()
        valid_x_i=x_i[:,:valid_len]

        # 翻转有效元素
        reversed_valid_x_i = valid_x_i.flip([-1])
        # 在结果张量中替换原来的元素
        result.append(torch.cat([reversed_valid_x_i,x_i[:,valid_len:]],dim=-1))
    result=torch.stack(result,dim=0)
    return result

class MaskedBiMamba(Mamba):
    def __init__(
        self,
        **kwargs
    ):
        #继承自videomamba：/home/feng_yi_sen/VideoMamba/mamba/mamba_ssm/modules/mamba_simple.py
        super(MaskedBiMamba,self).__init__(**kwargs)
        
    def forward(self, hidden_states,mask, inference_params=None, T=1):
        """
        hidden_states: (B, L, D)
        mask:(B,L)
        Returns: same shape as hidden_states
        """
        batch, seqlen, dim = hidden_states.shape

        conv_state, ssm_state = None, None
        if inference_params is not None:
            conv_state, ssm_state = self._get_states_from_cache(inference_params, batch)
            if inference_params.seqlen_offset > 0:
                # The states are updated inplace
                out, _, _ = self.step(hidden_states, conv_state, ssm_state)
                return out

        # We do matmul and transpose BLH -> HBL at the same time
        # NOTE: same as in_proj(hidden_states) but memory-efficient with the following operations
        xz = rearrange(
            self.in_proj.weight @ rearrange(hidden_states, "b l d -> d (b l)"),
            "d (b l) -> b d l",
            l=seqlen,
        )
        if self.in_proj.bias is not None:
            xz = xz + rearrange(self.in_proj.bias.to(dtype=xz.dtype), "d -> d 1")

        A = -torch.exp(self.A_log.float())  # (d_inner, d_state)
        # In the backward pass we write dx and dz next to each other to avoid torch.cat
        if self.use_fast_path and inference_params is None:  # Doesn't support outputting the states
            if self.bimamba:
                A_b = -torch.exp(self.A_b_log.float())
                out = mamba_inner_fn_no_out_proj(
                    xz,
                    self.conv1d.weight,
                    self.conv1d.bias,
                    self.x_proj.weight,
                    self.dt_proj.weight,
                    A,
                    None,  # input-dependent B
                    None,  # input-dependent C
                    self.D.float(),
                    delta_bias=self.dt_proj.bias.float(),
                    delta_softplus=True,
                )
                out_b = mamba_inner_fn_no_out_proj(
                    reverse_tensor_based_on_mask(xz,mask),
                    self.conv1d_b.weight,
                    self.conv1d_b.bias,
                    self.x_proj_b.weight,
                    self.dt_proj_b.weight,
                    A_b,
                    None,
                    None,
                    self.D_b.float(),
                    delta_bias=self.dt_proj_b.bias.float(),
                    delta_softplus=True,
                )
                out = F.linear(rearrange(out + reverse_tensor_based_on_mask(out_b,mask), "b d l -> b l d"), self.out_proj.weight, self.out_proj.bias)
            else:
                out = mamba_inner_fn(
                    xz,
                    self.conv1d.weight,
                    self.conv1d.bias,
                    self.x_proj.weight,
                    self.dt_proj.weight,
                    self.out_proj.weight,
                    self.out_proj.bias,
                    A,
                    None,  # input-dependent B
                    None,  # input-dependent C
                    self.D.float(),
                    delta_bias=self.dt_proj.bias.float(),
                    delta_softplus=True,
                )
        else:
            x, z = xz.chunk(2, dim=1)
            # Compute short convolution
            if conv_state is not None:
                conv_state.copy_(x[:, :, -self.d_conv :])  # Update state (B D W)
            if causal_conv1d_fn is None:
                x = self.act(self.conv1d(x)[..., :seqlen])
            else:
                assert self.activation in ["silu", "swish"]
                x = causal_conv1d_fn(
                    x,
                    rearrange(self.conv1d.weight, "d 1 w -> d w"),
                    self.conv1d.bias,
                    self.activation,
                )

            # We're careful here about the layout, to avoid extra transposes.
            # We want dt to have d as the slowest moving dimension
            # and L as the fastest moving dimension, since those are what the ssm_scan kernel expects.
            x_dbl = self.x_proj(rearrange(x, "b d l -> (b l) d"))  # (bl d)
            dt, B, C = torch.split(x_dbl, [self.dt_rank, self.d_state, self.d_state], dim=-1)
            dt = self.dt_proj.weight @ dt.t()
            dt = rearrange(dt, "d (b l) -> b d l", l=seqlen)
            B = rearrange(B, "(b l) dstate -> b dstate l", l=seqlen).contiguous()
            C = rearrange(C, "(b l) dstate -> b dstate l", l=seqlen).contiguous()
            assert self.activation in ["silu", "swish"]
            y = selective_scan_fn(
                x,
                dt,
                A,
                B,
                C,
                self.D.float(),
                z=z,
                delta_bias=self.dt_proj.bias.float(),
                delta_softplus=True,
                return_last_state=ssm_state is not None,
            )
            if ssm_state is not None:
                y, last_state = y
                ssm_state.copy_(last_state)
            y = rearrange(y, "b d l -> b l d")
            out = self.out_proj(y)
        return out
    

def test_masked_bi_mamba(device):
    """测试 MaskedBiMamba 类的基本功能"""
    
    # 测试配置参数
    batch_size = 2
    seq_len = 64
    hidden_dim = 128
    d_state = 16
    d_conv = 4
    expand = 2
    
    # 创建模型实例
    model_config = {
        'd_model': hidden_dim,
        'd_state': d_state,
        'd_conv': d_conv,
        'expand': expand,
        'bimamba': True,  # 确保启用双向Mamba
    }
    
    model = MaskedBiMamba(**model_config).to(device)
    model.eval()  # 设置为评估模式
    
    print("模型配置:")
    print(f"  d_model: {hidden_dim}")
    print(f"  d_state: {d_state}")
    print(f"  d_conv: {d_conv}")
    print(f"  expand: {expand}")
    print(f"  bimamba: {model_config['bimamba']}")
    
    # 测试1: 基本前向传播
    print("\n测试1: 基本前向传播")
    try:
        # 创建随机输入和mask
        hidden_states = torch.randn(batch_size, seq_len, hidden_dim).to(device)
        mask = torch.ones(batch_size, seq_len).to(device)
        mask[0, 32:] = 0  # 第一个batch的后半部分mask掉
        mask[1, :16] = 0  # 第二个batch的前半部分mask掉
        
        # 前向传播
        with torch.no_grad():
            output = model(hidden_states, mask)
        
        print(f"✓ 前向传播成功")
        print(f"  输入形状: {hidden_states.shape}")
        print(f"  输出形状: {output.shape}")
        print(f"  mask形状: {mask.shape}")
        assert output.shape == hidden_states.shape, f"输出形状 {output.shape} 与输入形状 {hidden_states.shape} 不匹配"
        
    except Exception as e:
        print(f"✗ 基本前向传播失败: {e}")
        return False
    
    # 测试2: 检查反向传播
    print("\n测试2: 反向传播")
    try:
        model.train()  # 设置为训练模式
        hidden_states = torch.randn(batch_size, seq_len, hidden_dim, requires_grad=True).to(device)
        mask = torch.ones(batch_size, seq_len).to(device)
        
        output = model(hidden_states, mask)
        loss = output.sum()
        loss.backward()
        
        print(f"✓ 反向传播成功")
        print(f"  损失值: {loss.item():.6f}")
        
        # 检查梯度
        has_grad = hidden_states.grad is not None
        print(f"  输入是否有梯度: {has_grad}")
        if has_grad:
            print(f"  输入梯度范数: {hidden_states.grad.norm().item():.6f}")
        
    except Exception as e:
        print(f"✗ 反向传播失败: {e}")
        return False
    
    # 测试3: 不同序列长度
    print("\n测试3: 不同序列长度")
    try:
        model.eval()
        seq_lengths = [32, 64, 128]
        
        for seq_len in seq_lengths:
            hidden_states = torch.randn(batch_size, seq_len, hidden_dim).to(device)
            mask = torch.ones(batch_size, seq_len).to(device)
            
            with torch.no_grad():
                output = model(hidden_states, mask)
            
            assert output.shape == (batch_size, seq_len, hidden_dim)
            print(f"✓ 序列长度 {seq_len}: 输出形状 {output.shape}")
            
    except Exception as e:
        print(f"✗ 不同序列长度测试失败: {e}")
        return False
    
    # 测试4: 检查mask效果
    print("\n测试4: mask效果检查")
    try:
        model.eval()
        
        # 创建全1的mask和部分mask的对比
        hidden_states = torch.randn(1, 10, hidden_dim).to(device)
        full_mask = torch.ones(1, 10).to(device)
        partial_mask = torch.ones(1, 10).to(device)
        partial_mask[0, 5:] = 0  # 后半部分mask掉
        
        with torch.no_grad():
            output_full = model(hidden_states, full_mask)
            output_partial = model(hidden_states, partial_mask)
        
        # 检查输出是否不同（由于双向性，mask应该影响结果）
        diff = torch.abs(output_full - output_partial).mean()
        print(f"  full_mask 和 partial_mask 输出差异: {diff.item():.6f}")
        
        if diff > 1e-6:
            print("✓ mask确实影响了输出（符合预期）")
        else:
            print("? mask对输出影响较小，可能需要检查实现")
            
    except Exception as e:
        print(f"✗ mask效果检查失败: {e}")
        return False
    
    # 测试5: 推理参数测试
    print("\n测试5: 推理参数测试")
    try:
        from mamba_ssm.ops.triton.selective_state_update import selective_state_update
        
        class InferenceParams:
            def __init__(self, seqlen_offset, max_seqlen, batch_size):
                self.seqlen_offset = seqlen_offset
                self.max_seqlen = max_seqlen
                self.batch_size = batch_size
                self.key_value_memory_dict = {}
                self.fused_ft_kernel = False
                self.sequences = None
        
        # 模拟推理时的状态缓存
        inference_params = InferenceParams(seqlen_offset=0, max_seqlen=seq_len, batch_size=batch_size).to(device)
        
        hidden_states = torch.randn(batch_size, 1, hidden_dim).to(device)  # 单步输入
        mask = torch.ones(batch_size, 1).to(device)
        
        with torch.no_grad():
            output_step1 = model(hidden_states, mask, inference_params=inference_params)
            
            # 模拟下一步
            inference_params.seqlen_offset = 1
            output_step2 = model(hidden_states, mask, inference_params=inference_params)
        
        print(f"✓ 推理参数测试成功")
        print(f"  单步输出形状: {output_step1.shape}")
        
    except Exception as e:
        print(f"⚠ 推理参数测试遇到问题（可能是预期内的）: {e}")
    
    # 测试6: 数值稳定性检查
    print("\n测试6: 数值稳定性检查")
    try:
        model.eval()
        
        # 极端输入值
        extreme_inputs = [
            torch.zeros(batch_size, seq_len, hidden_dim).to(device),  # 全零
            torch.ones(batch_size, seq_len, hidden_dim).to(device),   # 全一
            torch.randn(batch_size, seq_len, hidden_dim).to(device) * 10,  # 大数值
        ]
        
        mask = torch.ones(batch_size, seq_len).to(device)
        
        for i, hidden_states in enumerate(extreme_inputs):
            with torch.no_grad():
                output = model(hidden_states, mask)
            
            has_nan = torch.isnan(output).any()
            has_inf = torch.isinf(output).any()
            
            print(f"  输入情况 {i+1}: NaN={has_nan}, Inf={has_inf}")
            
            if has_nan or has_inf:
                print(f"✗ 数值稳定性问题: 输入{i+1}产生了NaN或Inf")
                return False
        
        print("✓ 数值稳定性检查通过")
        
    except Exception as e:
        print(f"✗ 数值稳定性检查失败: {e}")
        return False
    
    print("\n🎉 所有测试通过！MaskedBiMamba 类运行正常")
    return True

# 辅助函数（如果不在同一文件中需要定义）
def reverse_tensor_based_on_mask(tensor, mask):
    """
    基于mask反转tensor的辅助函数
    """
    # 这里需要根据你的实际实现来定义
    # 假设这是一个简单的反转函数
    return torch.flip(tensor, dims=[-1])

# 运行测试
if __name__ == "__main__":
    device = torch.device("cuda:7" if torch.cuda.is_available() else "cpu")

    # 确保必要的导入
    try:
        from mamba_ssm.modules.mamba_simple import Mamba
        from mamba_ssm.ops.selective_scan_interface import selective_scan_fn, mamba_inner_fn, mamba_inner_fn_no_out_proj
        from einops import rearrange
        import torch.nn.functional as F
        
        # 运行测试
        success = test_masked_bi_mamba(device=device)
        
        if success:
            print("\n✅ MaskedBiMamba 测试完全成功！")
        else:
            print("\n❌ MaskedBiMamba 测试失败，请检查实现。")
            
    except ImportError as e:
        print(f"❌ 导入失败: {e}")
        print("请确保所有依赖包已正确安装")